on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install NPM Packages
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: Validate JSON
      shell: bash
      run: f() { for i in *.json; do npx jsonlint "$i" || return 1; done; }; f
    - name: Lint Code
      run: npm run lint:code
    - name: Audit NPM Packages
      if: matrix.node >= 10
      run: npm audit
    - name: Lint Dependencies
      shell: bash
      run: npm run lint:deps
    - name: Integration Test
      run: 'npx newman run postman_collection.json --global-var "apiKey=${{ secrets.ApiKey }}" --global-var "baseUrl=${{ secrets.ApiUrl }}"'
    - name: Publish
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: storage-fa
        publish-profile: ${{ secrets.ScmCredentials }}
